config/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(pattern_name='2players:main'), name='home'),
    re_path(r'^about$', TemplateView.as_view(template_name="about.html"), name='about'),

    path(settings.ADMIN_URL, admin.site.urls),

    re_path(r'^2players/', include('two_players.urls')),
    re_path(r'^ring/', include('ring.urls')),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

p_values/ring/urls.py
from django.conf.urls import include, re_path
from . import views

app_name = 'ring'
urlpatterns = [
    re_path(r'^$', views.RingView.as_view(), name='main'),
    re_path(r'^calculation$', views.RingCalculation.as_view(), name='calculation'),
]

p_values/two_player/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.TwoPlayerView.as_view(), name='main'),
    url(r'^calculation$', views.TwoPlayerCalculation.as_view(), name='calculation'),
]

p_values/two_players/urls.py
from django.conf.urls import include, re_path
from . import views

app_name = '2players'
urlpatterns = [
    re_path(r'^$', views.TwoPlayerView.as_view(), name='main'),
    re_path(r'^calculation$', views.TwoPlayerCalculation.as_view(), name='calculation'),
]

p_values/users/urls.py
from django.urls import path

from p_values.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

p_values/ring/models.py
from django.db import models

# Create your models here.

p_values/two_players/models.py
from django.db import models

# Create your models here.

p_values/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

p_values/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

p_values/ring/views.py
from django.views.generic import TemplateView
from django.views import View
from django.http import JsonResponse

from .helpers import check_p_val, full_payoffs, full_probabilities

import numpy as np
import json

class RingView(TemplateView):
    template_name = "ring.html"

class RingCalculation(View):

    def get(self, request):
        params = request.GET
        payoffs = np.array(json.loads(params.get('payoffs'))).astype(float)
        probabilities = np.array(json.loads(params.get('probabilities'))).astype(float)
        probabilities = probabilities.T # Need to transpose
        p_value = float(params["p_value"])

        result = check_p_val(full_payoffs(payoffs),
                             full_probabilities(probabilities),
                             p_value)

        return JsonResponse({"success": result["success"],
                             "matrix": result["x"].tolist(),
                             "dims": probabilities.shape})

p_values/two_player/views.py
from django.views.generic import TemplateView
from django.views import View
from django.http import JsonResponse

from .helpers import check_p_val, to_matrix

import numpy as np

class TwoPlayerView(TemplateView):
    template_name = "2players/2players.html"

class TwoPlayerCalculation(View):

    def get(self, request):
        params = request.GET
        a_payoff = np.array(to_matrix(params.getlist('player_a[]'))).astype(float)
        b_payoff = np.array(to_matrix(params.getlist('player_b[]'))).astype(float)
        probabilities = np.array(to_matrix(params.getlist('probabilities[]'))).astype(float)
        p_value = float(params["p_value"])

        result = check_p_val((a_payoff, b_payoff), probabilities, p_value)

        return JsonResponse({"success": result["success"],
                             "matrix": result["x"].tolist(),
                             "dims": probabilities.shape})

p_values/two_players/views.py
from django.views.generic import TemplateView
from django.views import View
from django.http import JsonResponse

from .helpers import check_p_val

import numpy as np
import json

class TwoPlayerView(TemplateView):
    template_name = "2players.html"

class TwoPlayerCalculation(View):

    def get(self, request):
        params = request.GET
        a_payoff = np.array(json.loads(params.get('player_a'))).astype(float)
        b_payoff = np.array(json.loads(params.get('player_b'))).astype(float)
        probabilities = np.array(json.loads(params.get('probabilities'))).astype(float)
        p_value = float(params.get("p_value"))

        result = check_p_val((a_payoff, b_payoff), probabilities, p_value)

        return JsonResponse({"success": result["success"],
                             "matrix": result["x"].tolist(),
                             "dims": probabilities.shape})

p_values/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

p_values/templates/2players.html
{% extends "base.html" %}

{% load static i18n %}

{% block javascript %}
<script src="{% static 'js/2player.bundle.js' %}"></script>

<script src="{% static 'js/vendors~2player~about~ring.bundle.js' %}"></script>
<script src="{% static 'js/vendors~2player~ring.bundle.js' %}"></script>

{% endblock javascript %}

{% block 2player_active %}active{% endblock %}

{% block content %} {% verbatim %}
<div id="app">
  <h1>2 player games</h1>

  <div class="row mb-3">
    <div class="col-sm-auto">
      <label for="playerAStrategies" class="col-sm-auto">Number of strategies of player A</label>
    </div>
    <div class="col-sm-6">
      <counter v-model="playerAStrategies" id="playerAStrategies"
      :upper-limit="maxStrategies" :lower-limit="2"></counter>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-auto">
      <label for="playerBStrategies" class="col-sm-auto">Number of strategies of player B</label>
    </div>
    <div class="col-sm-6">
      <counter v-model="playerBStrategies" id="playerBStrategies"
      :upper-limit="maxStrategies" :lower-limit="2"></counter>
    </div>
  </div>

  <div class="card">
    <div class="card-header" role="tab" id="headingA">
      <h5 class="mb-0">
        <a data-toggle="collapse" href="#collapseA" role="button" aria-expanded="true" aria-controls="collapseA">
          Player A payoffs
        </a>
      </h5>
    </div>

    <div id="collapseA" class="collapse show" role="tabpanel" aria-labelledby="headingA">
      <div class="card-body table-responsive">
        <edit-table v-model="payoffsA"></edit-table>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" role="tab" id="headingB">
      <h5 class="mb-0">
        <a data-toggle="collapse" href="#collapseB" role="button" aria-expanded="true" aria-controls="collapseB">
          Player B payoffs
        </a>
      </h5>
    </div>

    <div id="collapseB" class="collapse show" role="tabpanel" aria-labelledby="headingB">
      <div class="card-body table-responsive">
        <edit-table v-model="payoffsB"></edit-table>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" role="tab" id="headingProb">
      <h5 class="mb-0">
        <a data-toggle="collapse" href="#collapseProb" role="button" aria-expanded="true" aria-controls="collapseProb">
          Empirical frequencies (probabilities)
        </a>
      </h5>
    </div>

    <div id="collapseProb" class="collapse show" role="tabpanel" aria-labelledby="headingProb">
      <div class="card-body table-responsive">
        <edit-table v-model="probabilities"></edit-table>
      </div>
    </div>
  </div>

  <hr>

  <div class="alert alert-danger mt-3" v-show="probabilitiesError">
    The probabilities do not sum up to 1!
  </div>

  <div class="row">
    <div class="col">
      <button :disabled="calculating" @click="calculate()" class="btn btn-primary">
        {{buttonStatus}}
      </button>
    </div>
    <div class="col">
      <div class="btn-group float-right">
        <button type="button" class="btn btn-secpndary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Examples
        </button>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" @click="setExample(0)">(2x2) Penalty kicks</a>
          <a class="dropdown-item" @click="setExample(1)">(2x4) Kreps' game</a>
          <a class="dropdown-item" @click="setExample(2)">(2x2) Matching pennies</a>
          <a class="dropdown-item" @click="setExample(3)">(2x2) Asymmetric matching pennies</a>
          <a class="dropdown-item" @click="setExample(4)">(2x2) Inspection game (chimps)</a>
          <a class="dropdown-item" @click="setExample(5)">(2x2) Inspection game (humans)</a>
          <a class="dropdown-item" @click="setExample(6)">(2x2) 2 rounds dom. solvable</a>
          <a class="dropdown-item" @click="setExample(7)">(3x2) 3 rounds dom. solvable</a>
        </div>
      </div>
    </div>
  </div>
  <hr>

  <div v-show="calculated">
    <h2>Results</h2>
    <span>Estimated p-value:</span> {{bisection.middle | round(3) }} </br>
    <span>P-value range:</span> [{{bisection.lower | round(3) }}, {{bisection.upper | round(3) }}]</br>
  </div>

  <hr>
  {% endverbatim %}{% endblock content %}

p_values/templates/2players/2players.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{{ block.super }}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

{% endblock css %}

{% block content %}
<h1> 2 player games </h1>
<p>Here you can calculate the p-rationality value for 2 player games with up to 10 strategies.</p>

<div class="container-fluid">
  <div class="row">
    <label for="a-rows" class="col-md-auto">Number of A's strategies:</label>
    <div class="input-group spinner mb-3 col-md-2" data-trigger="spinner" id="a-rows" >

      <div class="input-group-prepend">
        <button class="btn spin-down" type="button" data-spin="down"><i class="fa fa-caret-down"></i></button>
      </div>
      <input type="text" class="form-control text-center" value="2" data-rule="quantity" data-max=10 id="an">
      <div class="input-group-append">
        <button class="btn spin-up" data-spin="up"><i class="fa fa-caret-up"></i></button>
      </div>
    </div>
    <div class="w-100"></div>

    <label for="b-rows" class="col-md-auto">Number of B's strategies:</label>

    <div class="input-group spinner mb-3 col-md-2" data-trigger="spinner" id="b-rows" data-max=10>

      <div class="input-group-prepend">
        <button class="btn spin-down" type="button" data-spin="down"><i class="fa fa-caret-down"></i></button>
      </div>
      <input type="text" class="form-control text-center" value="2" data-rule="quantity" data-max=10 id="bn">
      <div class="input-group-append">
        <button class="btn spin-up" data-spin="up"><i class="fa fa-caret-up"></i></button>
      </div>
    </div>
  </div>
</div>


<div class="card">
  <div class="card-header" role="tab" id="headingA">
    <h5 class="mb-0">
      <a data-toggle="collapse" href="#collapseA" role="button" aria-expanded="true" aria-controls="collapseA">
        Player A payoffs
      </a>
    </h5>
  </div>

  <div id="collapseA" class="collapse show" role="tabpanel" aria-labelledby="headingA">
    <div class="card-body">
      <table class="table table-responsive" id="table_a">
      </table>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-header" role="tab" id="headingB">
    <h5 class="mb-0">
      <a data-toggle="collapse" href="#collapseB" role="button" aria-expanded="true" aria-controls="collapseB">
        Player B payoffs
      </a>
    </h5>
  </div>

  <div id="collapseB" class="collapse show" role="tabpanel" aria-labelledby="headingB">
    <div class="card-body">
      <table class="table table-responsive" id="table_b">
      </table>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-header" role="tab" id="headingProb">
    <h5 class="mb-0">
      <a data-toggle="collapse" href="#collapseProb" role="button" aria-expanded="true" aria-controls="collapseProb">
        Empirical frequencies (probabilities)
      </a>
    </h5>
  </div>

  <div id="collapseProb" class="collapse show" role="tabpanel" aria-labelledby="headingProb">
    <div class="card-body">
      <table class="table table-responsive" id="table_p">
      </table>
    </div>
  </div>
</div>

<div class="m-3">
  <button id="calcButton" type="button" class="btn btn-primary" onclick="calculate();">Calculate</button>
  <button type="button" class="btn btn-secondary" onclick="clearAll();">Clear All</button>
<div/>

<hr/>

<div id="results">
  <h4> Results: </h4>
  <div id="results-txt">
  </div>
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
<script>
var calculate_url = "{% url 'two_players:calculation' %}"
</script>

<script src="{% static 'js/editable_table.js' %}"></script>
<script src="{% static 'js/spinner.js' %}"></script>
<script src="{% static 'js/2player.js' %}"></script>

{% endblock javascript %}

p_values/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

p_values/templates/about.html
{% extends "base.html" %}
{% load static i18n %}

{% block javascript %}

<script src="{% static 'js/vendors~2player~about~ring.bundle.js' %}"></script>
<script src="{% static 'js/about.bundle.js' %}"></script>

{% endblock javascript %}

{% block about_active %}active{% endblock %}

{% block content %}
<div class="about">
  <h1> About </h1>
  This webapp enables the calculation of p-rationality values based on a paper
  by Fabrizio Germano and Peio Zuazo-Garin<a id="paper1f" class="footnote" href="#paper1">1</a> titled <i>Bounded rationality and correlated equilibria</i>. The uses the linprog module of the <a href="https://www.scipy.org/">scipy</a> package to check for the existence of a solution for a given p value,
  and uses simple bisection to approximate the upper bound.
  </br>

  <div class="footnotes">
    <hr>
    <ol>
      <li id="paper1">
        <p> Germano, F. & Zuazo-Garin, P. Int J Game Theory (2017) 46: 595. <a href="https://doi.org/10.1007/s00182-016-0547-5">[Link]</a>  <a href="#paper1f" class="footnoteBackLink" title="Jump back to footnote 1 in the text.">↩︎</a></p>
      </li>
    </ol>
  </div>
</div>
{% endblock content %}

p_values/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}P-values {% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    
    {% block css %}

    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url '2players:main' %}">P-values </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block 2player_active %}{% endblock %}">
              <a class="nav-link" href="{% url '2players:main' %}">2-players</a>
            </li>
            <li class="nav-item {% block ring_active %}{% endblock %}">
              <a class="nav-link" href="{% url 'ring:main' %}">Ring</a>
            </li>
            <li class="nav-item {% block about_active %}{% endblock %}">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
           <li class="nav-item">
             <a class="nav-link" href="https://github.com/tadejsv/p_values">
                 <span class="d-none d-sm-inline"> View on GitHub </span>
                 <svg version="1.1" width="16" height="16" viewBox="0 0 16 16" class="octicon octicon-mark-github" aria-hidden="true"><path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>
             </a>
           </li>
         </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

    {% endblock javascript %}
  </body>
</html>

p_values/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

p_values/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

p_values/templates/pages/about.html
{% extends "base.html" %}

{% block content %}
<h1> About </h1>
This webapp enables the calculation of p-rationality values based on <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2717741">this paper</a>
by Fabrizio Germano and Peio Zuazo-Garin. The uses the linprog module of the <a href="https://www.scipy.org/">scipy</a> package to check for the existence of a solution for a given p value,
and uses simple bisection to approximate the upper bound.
</br>

{% endblock content %}

p_values/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

p_values/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

p_values/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}